#
# Module manifest for module 'Microsoft.Graph.Identity.SignIns'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/9/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Identity.SignIns.psm1'

# Version number of this module.
ModuleVersion = '2.28.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '60f889fa-f873-43ad-b7d3-b7fc1273a44f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.28.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Identity.SignIns.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Identity.SignIns.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Confirm-MgRiskyServicePrincipalCompromised', 
               'Confirm-MgRiskyUserCompromised', 
               'Disable-MgUserAuthenticationPhoneMethodSmsSignIn', 
               'Enable-MgUserAuthenticationPhoneMethodSmsSignIn', 
               'Get-MgDataPolicyOperation', 'Get-MgDataPolicyOperationCount', 
               'Get-MgIdentityApiConnector', 'Get-MgIdentityApiConnectorCount', 
               'Get-MgIdentityAuthenticationEventFlow', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlow', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowCondition', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowIncludeApplication', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowIncludeApplicationCount', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowOnAttributeCollection', 
               'Get-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowOnAuthenticationMethodLoadStart', 
               'Get-MgIdentityAuthenticationEventFlowAsOnAttributeCollectionExternalUserSelfServiceSignUpAttribute', 
               'Get-MgIdentityAuthenticationEventFlowAsOnAttributeCollectionExternalUserSelfServiceSignUpAttributeCount', 
               'Get-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProvider', 
               'Get-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProviderByRef', 
               'Get-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProviderCount', 
               'Get-MgIdentityAuthenticationEventFlowAsOnGraphAPretributeCollectionExternalUserSelfServiceSignUpAttributeByRef', 
               'Get-MgIdentityAuthenticationEventFlowCondition', 
               'Get-MgIdentityAuthenticationEventFlowCount', 
               'Get-MgIdentityAuthenticationEventFlowCountAsExternalUserSelfServiceSignUpEventFlow', 
               'Get-MgIdentityAuthenticationEventFlowIncludeApplication', 
               'Get-MgIdentityAuthenticationEventFlowIncludeApplicationCount', 
               'Get-MgIdentityAuthenticationEventFlowOnAttributeCollectionAsOnAttributeCollectionExternalUserSelfServiceSignUp', 
               'Get-MgIdentityAuthenticationEventFlowOnAuthenticationMethodLoadStartAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUp', 
               'Get-MgIdentityAuthenticationEventListener', 
               'Get-MgIdentityAuthenticationEventListenerCount', 
               'Get-MgIdentityB2XUserFlow', 
               'Get-MgIdentityB2XUserFlowApiConnectorConfiguration', 
               'Get-MgIdentityB2XUserFlowCount', 
               'Get-MgIdentityB2XUserFlowIdentityProvider', 
               'Get-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'Get-MgIdentityB2XUserFlowIdentityProviderCount', 
               'Get-MgIdentityB2XUserFlowLanguage', 
               'Get-MgIdentityB2XUserFlowLanguageCount', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPageContent', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPageCount', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePageContent', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePageCount', 
               'Get-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Get-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Get-MgIdentityB2XUserFlowPostFederationSignup', 
               'Get-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentCount', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentOrder', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentUserAttribute', 
               'Get-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Get-MgIdentityConditionalAccessAuthenticationContextClassReferenceCount', 
               'Get-MgIdentityConditionalAccessNamedLocation', 
               'Get-MgIdentityConditionalAccessNamedLocationCount', 
               'Get-MgIdentityConditionalAccessPolicy', 
               'Get-MgIdentityConditionalAccessPolicyCount', 
               'Get-MgIdentityConditionalAccessTemplate', 
               'Get-MgIdentityConditionalAccessTemplateCount', 
               'Get-MgIdentityCustomAuthenticationExtension', 
               'Get-MgIdentityCustomAuthenticationExtensionCount', 
               'Get-MgIdentityProvider', 'Get-MgIdentityProviderCount', 
               'Get-MgIdentityUserFlowAttribute', 
               'Get-MgIdentityUserFlowAttributeCount', 
               'Get-MgInformationProtection', 
               'Get-MgInformationProtectionBitlocker', 
               'Get-MgInformationProtectionBitlockerRecoveryKey', 
               'Get-MgInformationProtectionBitlockerRecoveryKeyCount', 
               'Get-MgInformationProtectionThreatAssessmentRequest', 
               'Get-MgInformationProtectionThreatAssessmentRequestCount', 
               'Get-MgInformationProtectionThreatAssessmentRequestResult', 
               'Get-MgInformationProtectionThreatAssessmentRequestResultCount', 
               'Get-MgInvitation', 'Get-MgInvitationCount', 
               'Get-MgInvitationInvitedUserMailboxSetting', 
               'Get-MgInvitationInvitedUserServiceProvisioningError', 
               'Get-MgInvitationInvitedUserServiceProvisioningErrorCount', 
               'Get-MgInvitationInvitedUserSponsor', 
               'Get-MgInvitationInvitedUserSponsorCount', 
               'Get-MgOauth2PermissionGrant', 'Get-MgOauth2PermissionGrantCount', 
               'Get-MgOauth2PermissionGrantDelta', 
               'Get-MgOrganizationCertificateBasedAuthConfiguration', 
               'Get-MgOrganizationCertificateBasedAuthConfigurationCount', 
               'Get-MgPolicyActivityBasedTimeoutPolicy', 
               'Get-MgPolicyActivityBasedTimeoutPolicyApplyTo', 
               'Get-MgPolicyActivityBasedTimeoutPolicyApplyToCount', 
               'Get-MgPolicyActivityBasedTimeoutPolicyCount', 
               'Get-MgPolicyAdminConsentRequestPolicy', 
               'Get-MgPolicyAppManagementPolicy', 
               'Get-MgPolicyAppManagementPolicyApplyTo', 
               'Get-MgPolicyAppManagementPolicyApplyToCount', 
               'Get-MgPolicyAppManagementPolicyCount', 
               'Get-MgPolicyAuthenticationFlowPolicy', 
               'Get-MgPolicyAuthenticationMethodPolicy', 
               'Get-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Get-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfigurationCount', 
               'Get-MgPolicyAuthenticationStrengthPolicy', 
               'Get-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Get-MgPolicyAuthenticationStrengthPolicyCombinationConfigurationCount', 
               'Get-MgPolicyAuthenticationStrengthPolicyCount', 
               'Get-MgPolicyAuthorizationPolicy', 'Get-MgPolicyClaimMappingPolicy', 
               'Get-MgPolicyClaimMappingPolicyApplyTo', 
               'Get-MgPolicyClaimMappingPolicyApplyToCount', 
               'Get-MgPolicyClaimMappingPolicyCount', 
               'Get-MgPolicyConditionalAccessPolicyCount', 
               'Get-MgPolicyCrossTenantAccessPolicy', 
               'Get-MgPolicyCrossTenantAccessPolicyDefault', 
               'Get-MgPolicyCrossTenantAccessPolicyPartner', 
               'Get-MgPolicyCrossTenantAccessPolicyPartnerCount', 
               'Get-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Get-MgPolicyCrossTenantAccessPolicyTemplate', 
               'Get-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationIdentitySynchronization', 
               'Get-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationPartnerConfiguration', 
               'Get-MgPolicyDefaultAppManagementPolicy', 
               'Get-MgPolicyDeviceRegistrationPolicy', 
               'Get-MgPolicyFeatureRolloutPolicy', 
               'Get-MgPolicyFeatureRolloutPolicyApplyTo', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToByRef', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToCount', 
               'Get-MgPolicyFeatureRolloutPolicyCount', 
               'Get-MgPolicyHomeRealmDiscoveryPolicy', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyApplyTo', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyApplyToCount', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyCount', 
               'Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Get-MgPolicyPermissionGrantPolicy', 
               'Get-MgPolicyPermissionGrantPolicyCount', 
               'Get-MgPolicyPermissionGrantPolicyExclude', 
               'Get-MgPolicyPermissionGrantPolicyExcludeCount', 
               'Get-MgPolicyPermissionGrantPolicyInclude', 
               'Get-MgPolicyPermissionGrantPolicyIncludeCount', 
               'Get-MgPolicyRoleManagementPolicy', 
               'Get-MgPolicyRoleManagementPolicyAssignment', 
               'Get-MgPolicyRoleManagementPolicyAssignmentCount', 
               'Get-MgPolicyRoleManagementPolicyAssignmentPolicy', 
               'Get-MgPolicyRoleManagementPolicyCount', 
               'Get-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Get-MgPolicyRoleManagementPolicyEffectiveRuleCount', 
               'Get-MgPolicyRoleManagementPolicyRule', 
               'Get-MgPolicyRoleManagementPolicyRuleCount', 
               'Get-MgPolicyTokenIssuancePolicy', 
               'Get-MgPolicyTokenIssuancePolicyApplyTo', 
               'Get-MgPolicyTokenIssuancePolicyApplyToCount', 
               'Get-MgPolicyTokenIssuancePolicyCount', 
               'Get-MgPolicyTokenLifetimePolicy', 
               'Get-MgPolicyTokenLifetimePolicyApplyTo', 
               'Get-MgPolicyTokenLifetimePolicyApplyToCount', 
               'Get-MgPolicyTokenLifetimePolicyCount', 'Get-MgRiskDetection', 
               'Get-MgRiskDetectionCount', 'Get-MgRiskyServicePrincipal', 
               'Get-MgRiskyServicePrincipalCount', 
               'Get-MgRiskyServicePrincipalHistory', 
               'Get-MgRiskyServicePrincipalHistoryCount', 'Get-MgRiskyUser', 
               'Get-MgRiskyUserCount', 'Get-MgRiskyUserHistory', 
               'Get-MgRiskyUserHistoryCount', 
               'Get-MgServicePrincipalRiskDetection', 
               'Get-MgServicePrincipalRiskDetectionCount', 
               'Get-MgTenantRelationshipMultiTenantOrganization', 
               'Get-MgTenantRelationshipMultiTenantOrganizationJoinRequest', 
               'Get-MgTenantRelationshipMultiTenantOrganizationTenant', 
               'Get-MgTenantRelationshipMultiTenantOrganizationTenantCount', 
               'Get-MgUserAuthenticationEmailMethod', 
               'Get-MgUserAuthenticationEmailMethodCount', 
               'Get-MgUserAuthenticationFido2Method', 
               'Get-MgUserAuthenticationFido2MethodCount', 
               'Get-MgUserAuthenticationMethod', 
               'Get-MgUserAuthenticationMethodCount', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethod', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethodCount', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethodDevice', 
               'Get-MgUserAuthenticationOperation', 
               'Get-MgUserAuthenticationOperationCount', 
               'Get-MgUserAuthenticationPasswordMethod', 
               'Get-MgUserAuthenticationPasswordMethodCount', 
               'Get-MgUserAuthenticationPhoneMethod', 
               'Get-MgUserAuthenticationPhoneMethodCount', 
               'Get-MgUserAuthenticationSoftwareOathMethod', 
               'Get-MgUserAuthenticationSoftwareOathMethodCount', 
               'Get-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Get-MgUserAuthenticationTemporaryAccessPassMethodCount', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethod', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethodCount', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethodDevice', 
               'Invoke-MgAvailableIdentityProviderType', 
               'Invoke-MgDismissRiskyServicePrincipal', 
               'Invoke-MgDismissRiskyUser', 
               'Invoke-MgUploadIdentityApiConnectorClientCertificate', 
               'Invoke-MgUploadIdentityB2XUserFlowApiConnectorConfigurationPostAttributeCollectionClientCertificate', 
               'Invoke-MgUploadIdentityB2XUserFlowApiConnectorConfigurationPostFederationSignupClientCertificate', 
               'Invoke-MgUsageIdentityConditionalAccessAuthenticationStrengthPolicy', 
               'Invoke-MgUsagePolicyAuthenticationStrengthPolicy', 
               'New-MgDataPolicyOperation', 'New-MgIdentityApiConnector', 
               'New-MgIdentityAuthenticationEventFlow', 
               'New-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowIncludeApplication', 
               'New-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProviderByRef', 
               'New-MgIdentityAuthenticationEventFlowAsOnGraphAPretributeCollectionExternalUserSelfServiceSignUpAttributeByRef', 
               'New-MgIdentityAuthenticationEventFlowIncludeApplication', 
               'New-MgIdentityAuthenticationEventListener', 
               'New-MgIdentityB2XUserFlow', 
               'New-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'New-MgIdentityB2XUserFlowLanguage', 
               'New-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'New-MgIdentityB2XUserFlowLanguageOverridePage', 
               'New-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'New-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'New-MgIdentityConditionalAccessAuthenticationStrengthPolicyCombinationConfiguration', 
               'New-MgIdentityConditionalAccessNamedLocation', 
               'New-MgIdentityConditionalAccessPolicy', 
               'New-MgIdentityCustomAuthenticationExtension', 
               'New-MgIdentityProvider', 'New-MgIdentityUserFlowAttribute', 
               'New-MgInformationProtectionThreatAssessmentRequest', 
               'New-MgInformationProtectionThreatAssessmentRequestResult', 
               'New-MgInvitation', 'New-MgOauth2PermissionGrant', 
               'New-MgOrganizationCertificateBasedAuthConfiguration', 
               'New-MgPolicyActivityBasedTimeoutPolicy', 
               'New-MgPolicyAppManagementPolicy', 
               'New-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'New-MgPolicyAuthenticationStrengthPolicy', 
               'New-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'New-MgPolicyClaimMappingPolicy', 
               'New-MgPolicyCrossTenantAccessPolicyPartner', 
               'New-MgPolicyFeatureRolloutPolicy', 
               'New-MgPolicyFeatureRolloutPolicyApplyTo', 
               'New-MgPolicyFeatureRolloutPolicyApplyToByRef', 
               'New-MgPolicyHomeRealmDiscoveryPolicy', 
               'New-MgPolicyPermissionGrantPolicy', 
               'New-MgPolicyPermissionGrantPolicyExclude', 
               'New-MgPolicyPermissionGrantPolicyInclude', 
               'New-MgPolicyRoleManagementPolicy', 
               'New-MgPolicyRoleManagementPolicyAssignment', 
               'New-MgPolicyRoleManagementPolicyEffectiveRule', 
               'New-MgPolicyRoleManagementPolicyRule', 
               'New-MgPolicyTokenIssuancePolicy', 
               'New-MgPolicyTokenLifetimePolicy', 'New-MgRiskDetection', 
               'New-MgRiskyServicePrincipal', 'New-MgRiskyServicePrincipalHistory', 
               'New-MgRiskyUser', 'New-MgRiskyUserHistory', 
               'New-MgServicePrincipalRiskDetection', 
               'New-MgTenantRelationshipMultiTenantOrganizationTenant', 
               'New-MgUserAuthenticationEmailMethod', 
               'New-MgUserAuthenticationMethod', 
               'New-MgUserAuthenticationOperation', 
               'New-MgUserAuthenticationPhoneMethod', 
               'New-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Remove-MgDataPolicyOperation', 'Remove-MgIdentityApiConnector', 
               'Remove-MgIdentityAuthenticationEventFlow', 
               'Remove-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowIncludeApplication', 
               'Remove-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProviderBaseByRef', 
               'Remove-MgIdentityAuthenticationEventFlowAsOnAuthenticationMethodLoadStartExternalUserSelfServiceSignUpIdentityProviderByRef', 
               'Remove-MgIdentityAuthenticationEventFlowAsOnGraphAPretributeCollectionExternalUserSelfServiceSignUpAttributeByRef', 
               'Remove-MgIdentityAuthenticationEventFlowAsOnGraphAPretributeCollectionExternalUserSelfServiceSignUpAttributeIdentityUserFlowAttributeByRef', 
               'Remove-MgIdentityAuthenticationEventFlowIncludeApplication', 
               'Remove-MgIdentityAuthenticationEventListener', 
               'Remove-MgIdentityB2XUserFlow', 
               'Remove-MgIdentityB2XUserFlowIdentityProviderBaseByRef', 
               'Remove-MgIdentityB2XUserFlowLanguage', 
               'Remove-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Remove-MgIdentityB2XUserFlowLanguageDefaultPageContent', 
               'Remove-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Remove-MgIdentityB2XUserFlowLanguageOverridePageContent', 
               'Remove-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Remove-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Remove-MgIdentityB2XUserFlowPostFederationSignup', 
               'Remove-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Remove-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Remove-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Remove-MgIdentityConditionalAccessNamedLocation', 
               'Remove-MgIdentityConditionalAccessPolicy', 
               'Remove-MgIdentityCustomAuthenticationExtension', 
               'Remove-MgIdentityProvider', 'Remove-MgIdentityUserFlowAttribute', 
               'Remove-MgInformationProtectionThreatAssessmentRequest', 
               'Remove-MgInformationProtectionThreatAssessmentRequestResult', 
               'Remove-MgOauth2PermissionGrant', 
               'Remove-MgOrganizationCertificateBasedAuthConfiguration', 
               'Remove-MgPolicyActivityBasedTimeoutPolicy', 
               'Remove-MgPolicyAdminConsentRequestPolicy', 
               'Remove-MgPolicyAppManagementPolicy', 
               'Remove-MgPolicyAuthenticationFlowPolicy', 
               'Remove-MgPolicyAuthenticationMethodPolicy', 
               'Remove-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Remove-MgPolicyAuthenticationStrengthPolicy', 
               'Remove-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Remove-MgPolicyAuthorizationPolicy', 
               'Remove-MgPolicyClaimMappingPolicy', 
               'Remove-MgPolicyCrossTenantAccessPolicy', 
               'Remove-MgPolicyCrossTenantAccessPolicyDefault', 
               'Remove-MgPolicyCrossTenantAccessPolicyPartner', 
               'Remove-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Remove-MgPolicyCrossTenantAccessPolicyTemplate', 
               'Remove-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationIdentitySynchronization', 
               'Remove-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationPartnerConfiguration', 
               'Remove-MgPolicyDefaultAppManagementPolicy', 
               'Remove-MgPolicyFeatureRolloutPolicy', 
               'Remove-MgPolicyFeatureRolloutPolicyApplyToDirectoryObjectByRef', 
               'Remove-MgPolicyHomeRealmDiscoveryPolicy', 
               'Remove-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Remove-MgPolicyPermissionGrantPolicy', 
               'Remove-MgPolicyPermissionGrantPolicyExclude', 
               'Remove-MgPolicyPermissionGrantPolicyInclude', 
               'Remove-MgPolicyRoleManagementPolicy', 
               'Remove-MgPolicyRoleManagementPolicyAssignment', 
               'Remove-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Remove-MgPolicyRoleManagementPolicyRule', 
               'Remove-MgPolicyTokenIssuancePolicy', 
               'Remove-MgPolicyTokenLifetimePolicy', 'Remove-MgRiskDetection', 
               'Remove-MgRiskyServicePrincipal', 
               'Remove-MgRiskyServicePrincipalHistory', 'Remove-MgRiskyUser', 
               'Remove-MgRiskyUserHistory', 
               'Remove-MgServicePrincipalRiskDetection', 
               'Remove-MgTenantRelationshipMultiTenantOrganizationTenant', 
               'Remove-MgUserAuthenticationEmailMethod', 
               'Remove-MgUserAuthenticationFido2Method', 
               'Remove-MgUserAuthenticationMicrosoftAuthenticatorMethod', 
               'Remove-MgUserAuthenticationOperation', 
               'Remove-MgUserAuthenticationPhoneMethod', 
               'Remove-MgUserAuthenticationSoftwareOathMethod', 
               'Remove-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Remove-MgUserAuthenticationWindowsHelloForBusinessMethod', 
               'Reset-MgPolicyCrossTenantAccessPolicyDefaultToSystemDefault', 
               'Reset-MgUserAuthenticationMethodPassword', 
               'Set-MgIdentityB2XUserFlowLanguageDefaultPageContent', 
               'Set-MgIdentityB2XUserFlowLanguageOverridePageContent', 
               'Set-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Set-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Set-MgIdentityB2XUserFlowUserAttributeAssignmentOrder', 
               'Set-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Test-MgIdentityCustomAuthenticationExtensionAuthenticationConfiguration', 
               'Update-MgDataPolicyOperation', 'Update-MgIdentityApiConnector', 
               'Update-MgIdentityAuthenticationEventFlow', 
               'Update-MgIdentityAuthenticationEventFlowAsExternalUserSelfServiceSignUpEventFlowIncludeApplication', 
               'Update-MgIdentityAuthenticationEventFlowIncludeApplication', 
               'Update-MgIdentityAuthenticationEventListener', 
               'Update-MgIdentityB2XUserFlow', 
               'Update-MgIdentityB2XUserFlowLanguage', 
               'Update-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Update-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Update-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Update-MgIdentityB2XUserFlowPostFederationSignup', 
               'Update-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Update-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Update-MgIdentityConditionalAccessNamedLocation', 
               'Update-MgIdentityConditionalAccessPolicy', 
               'Update-MgIdentityCustomAuthenticationExtension', 
               'Update-MgIdentityProvider', 'Update-MgIdentityUserFlowAttribute', 
               'Update-MgInformationProtection', 
               'Update-MgInformationProtectionThreatAssessmentRequest', 
               'Update-MgInformationProtectionThreatAssessmentRequestResult', 
               'Update-MgInvitationInvitedUserMailboxSetting', 
               'Update-MgOauth2PermissionGrant', 
               'Update-MgPolicyActivityBasedTimeoutPolicy', 
               'Update-MgPolicyAdminConsentRequestPolicy', 
               'Update-MgPolicyAppManagementPolicy', 
               'Update-MgPolicyAuthenticationFlowPolicy', 
               'Update-MgPolicyAuthenticationMethodPolicy', 
               'Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Update-MgPolicyAuthenticationStrengthPolicy', 
               'Update-MgPolicyAuthenticationStrengthPolicyAllowedCombination', 
               'Update-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Update-MgPolicyAuthorizationPolicy', 
               'Update-MgPolicyClaimMappingPolicy', 
               'Update-MgPolicyCrossTenantAccessPolicy', 
               'Update-MgPolicyCrossTenantAccessPolicyDefault', 
               'Update-MgPolicyCrossTenantAccessPolicyPartner', 
               'Update-MgPolicyCrossTenantAccessPolicyTemplate', 
               'Update-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationIdentitySynchronization', 
               'Update-MgPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationPartnerConfiguration', 
               'Update-MgPolicyDefaultAppManagementPolicy', 
               'Update-MgPolicyFeatureRolloutPolicy', 
               'Update-MgPolicyHomeRealmDiscoveryPolicy', 
               'Update-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Update-MgPolicyPermissionGrantPolicy', 
               'Update-MgPolicyPermissionGrantPolicyExclude', 
               'Update-MgPolicyPermissionGrantPolicyInclude', 
               'Update-MgPolicyRoleManagementPolicy', 
               'Update-MgPolicyRoleManagementPolicyAssignment', 
               'Update-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Update-MgPolicyRoleManagementPolicyRule', 
               'Update-MgPolicyTokenIssuancePolicy', 
               'Update-MgPolicyTokenLifetimePolicy', 'Update-MgRiskDetection', 
               'Update-MgRiskyServicePrincipal', 
               'Update-MgRiskyServicePrincipalHistory', 'Update-MgRiskyUser', 
               'Update-MgRiskyUserHistory', 
               'Update-MgServicePrincipalRiskDetection', 
               'Update-MgTenantRelationshipMultiTenantOrganization', 
               'Update-MgTenantRelationshipMultiTenantOrganizationJoinRequest', 
               'Update-MgTenantRelationshipMultiTenantOrganizationTenant', 
               'Update-MgUserAuthenticationEmailMethod', 
               'Update-MgUserAuthenticationMethod', 
               'Update-MgUserAuthenticationOperation', 
               'Update-MgUserAuthenticationPhoneMethod'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'Remove-MgPolicyFeatureRolloutPolicyApplyToByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoQwYJKoZIhvcNAQcCoIIoNDCCKDACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBc0dyA3DRRoA4R
# J4iKTFGtxySbEdZWabK+SFT/zu4CHaCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiMwghofAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEILoJO948cc/zAI2ogSuMu7DC
# 2gTjKAujoZ6YbbzXJ8f+MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAH27G9CD1uw/O/xqAgfRQIk99NyhY6hCSUaY9HVD7ZL7+z4p3xhm/W9i8
# 0ORrckm7ys0K5K1YGOvz/K6/oherjXmQPLysSb7K8IeVHU+6tGdRcl0YBW/5AVge
# HubfAC2Z/VJl0yeKyd1wqOvyFhcaw6YP1G45gjpTnujP5GpulF+Wkr8HNnPNq6No
# CTMOWbnk4+z5N0It6mlC4F1PBHw5AKVRHqUP1aEId3L/hlEIWGtr/6CJuwjjZnga
# fWa1YQlHT9WNeU5DeKNVtYBc0km7AUgf+WodH7QXaMuXpvo3nEnCJ7CtcxViOXk/
# c2TOW5wo1Cy1KLnClVzNFfrYpsmfHaGCF60wghepBgorBgEEAYI3AwMBMYIXmTCC
# F5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCB6ZhArWDeU7tOD8Ps14RSzaDeZ3/YaUoKT/RAPpxcBRwIGaBLOY27c
# GBMyMDI1MDUwOTE4MjIxNy4xNzhaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo1NTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEfswggcoMIIFEKADAgECAhMzAAACAdFFWZgQzEJPAAEAAAIBMA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzEyMloXDTI1MTAyMjE4MzEyMlowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjU1MUEt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtWrf+HzDu7sk50y5YHhe
# CIJG0uxRSFFcHNek+Td9ZmyJj20EEjaU8JDJu5pWc4pPAsBI38NEAJ1b+KBnlStq
# U8uvXF4qnEShDdi8nPsZZQsTZDKWAgUM2iZTOiWIuZcFs5ZC8/+GlrVLM5h1Y9nf
# Mh5B4DnUQOXMremAT9MkvUhg3uaYgmqLlmYyODmba4lXZBu104SLAFsXOfl/TLhp
# ToT46y7lI9sbI9uq3/Aerh3aPi2knHvEEazilXeooXNLCwdu+Is6o8kQLouUn3Kw
# UQm0b7aUtsv1X/OgPmsOJi6yN3LYWyHISvrNuIrJ4iYNgHdBBumQYK8LjZmQaTKF
# acxhmXJ0q2gzaIfxF2yIwM+V9sQqkHkg/Q+iSDNpMr6mr/OwknOEIjI0g6ZMOymi
# vpChzDNoPz9hkK3gVHZKW7NV8+UBXN4G0aBX69fKUbxBBLyk2cC+PhOoUjkl6UC8
# /c0huqj5xX8m+YVIk81e7t6I+V/E4yXReeZgr0FhYqNpvTjGcaO2WrkP5XmsYS7I
# vMPIf4DCyIJUZaqoBMToAJJHGRe+DPqCHg6bmGPm97MrOWv16/Co6S9cQDkXp9vM
# SSRQWXy4KtJhZfmuDz2vr1jw4NeixwuIDGw1mtV/TdSI+vpLJfUiLl/b9w/tJB92
# BALQT8e1YH8NphdOo1xCwkcCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBSwcq9blqLo
# PPiVrym9mFmFWbyyUjAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAOjQAyz0cVztT
# FGqXX5JLRxFK/O/oMe55uDqEC8Vd1gbcM28KBUPgvUIPXm/vdDN2IVBkWHmwCp4A
# Icy4dZtkuUmd0fnu6aT9Mvo1ndsLp2YJcMoFLEt3TtriLaO+i4Grv0ZULtWXUPAW
# /Mn5Scjgn0xZduGPBD/Xs3J7+get9+8ZvBipsg/N7poimYOVsHxLcem7V5XdMNsy
# tTm/uComhM/wgR5KlDYTVNAXBxcSKMeJaiD3V1+HhNkVliMl5VOP+nw5xWF55u9h
# 6eF2G7eBPqT+qSFQ+rQCQdIrN0yG1QN9PJroguK+FJQJdQzdfD3RWVsciBygbYaZ
# lT1cGJI1IyQ74DQ0UBdTpfeGsyrEQ9PI8QyqVLqb2q7LtI6DJMNphYu+jr//0spr
# 1UVvyDPtuRnbGQRNi1COwJcj9OYmlkFgKNeCfbDT7U3uEOvWomekX60Y/m5utRcU
# PVeAPdhkB+DxDaev3J1ywDNdyu911nAVPgRkyKgMK3USLG37EdlatDk8FyuCrx4t
# iHyqHO3wE6xPw32Q8e/vmuQPoBZuX3qUeoFIsyZEenHq2ScMunhcqW32SUVAi5oZ
# 4Z3nf7dAgNau21NEPwgW+2wkrNqDg7Hp8yHyoOKbgEBu6REQbvSfZ5Kh4PV+S2gx
# f2uq6GoYDnlqABOMYwz309ISi0bPMh8wggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo1NTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA1+26cR/yH100DiNFGWhuAv2rYBqggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOvIgRcwIhgPMjAyNTA1MDkxMzI2NDdaGA8yMDI1MDUxMDEzMjY0N1owdDA6
# BgorBgEEAYRZCgQBMSwwKjAKAgUA68iBFwIBADAHAgEAAgIENTAHAgEAAgISZDAK
# AgUA68nSlwIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
# AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQBkggcmoCB0lAUI
# rbbyVtQ+wwdhHmXm8jNhcydU0dCV+J+fCr3x6lvti/64aj1DUBPCTJGV38HPjVAi
# iDLDx0TIdNJDs42WfZvBqNvTeR2myrwNrIBk7C5FFrLkHqkcz6HnlF8K8Q+UJrYD
# 4M3IF78pPk8VcJwryiJzZrL9ifVsVU/5LEckqQPOKMthumpRKlWQM7FxgFhMKsSk
# AJzTjtcmXsSTQNTMiM78rIG+5hWGZMIEagzyW4rfFdI8pdv24slfjMBelrWfsAcb
# iUKo281OI3os4FNYd+Gwu9F/VBiHe1JLjgFSRaUKDfaq2GFt48oGZAsXeD9asmNv
# uJsBjqREMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAIB0UVZmBDMQk8AAQAAAgEwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqG
# SIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgwRdw+9F0OTPV
# viXkesZlXuJoR/rma23omR1iDqJbXBkwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHk
# MIG9BCBYa7I6TJQRcmx0HaSTWZdJgowdrl9+Zrr0pIdqHtc4IzCBmDCBgKR+MHwx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
# Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAACAdFFWZgQzEJPAAEAAAIB
# MCIEIOptH0Irz8op9HexLVHrIUp5iT4BQZZq0XHA7ODiyY2gMA0GCSqGSIb3DQEB
# CwUABIICAIP6j8oPQKrRA3Y8PCk/+Z5EeYOhU9XtcXTzABY9G5aM/7Gzs4v6NOHZ
# LUltwjvmE40BByzujAwJvQ0hhhW5+S1L4o5XOsAF/9CsGYaOc86anPTJmuBxIYhX
# /7tbWqUdD0Qob/6bUaK2NeIUh6K72OUUhmUn4ENliVdtKBtmqcl1ZbPxf/escF9H
# HH4r9P854VFTQj646H7FZ440xLoogUeJ+7MV7yzyvbOTGZ+SH6bi3cMKzXe0oPz9
# oEVfRPy3fyoQYa44bMbA8ZbU3kwgcujcAzzndl4sx7Cm/ZBlYbcGcdSiEaGlAjQg
# jyBctYOliY9iy3QQIZbqWnVlJ6uCq+rOrONfh7b+sVOhsz8uHOFXBfieQlI7tpuL
# Q0a1z0Q7ckWnBlXoFekPc2fmsbD2/s5OHVd6gC210dlzzvcquy8g+PDIHEiq3+no
# KOFM3efAlvZCXKAUlcnycrZB44T+mQEO1RfLcSM6CoYFf7uQ4m6Tdo4t1bcwRIS7
# /3pUHCVEJIc4X3ocu2QwUNcJ/jWrJjiYulUSBQELAHrQUqdCsg59+BPBgeC/78kR
# Qk4HX5wtmIrzG08Gnvk3HrxO/s+MuNjbVefBbUpNCVk01K6XyS/OOnatWq/R9R+M
# +7dFvV+1uzds2YrsFbDyfUti825fHhW5EsbMTZ9yG1g1lMKIf0b8
# SIG # End signature block
